In [1]:
import numpy as np

In [7]:
def softmax(vec):
    denumerator = np.exp(vec - np.max(vec, axis=-1, keepdims=True))
    numerator = np.sum(denumerator, axis=-1, keepdims=True)
    val = denumerator / numerator
    return val

In [16]:
vec = np.array([[1, 2, 0], [-1, 0, 1], [-10, 0, 10]])

print('max', np.max(vec, axis=-1, keepdims=True)) # [[2], [1], [10]]
print('diff', vec - np.max(vec, axis=-1, keepdims=True)) #[[-1, 0, -2], [-2, -1, 0], [-20, -10, 0]]
print('exp', np.exp(vec - np.max(vec, axis=-1, keepdims=True))) #[[e^-1, e^0, e^-2], [e^-2, e^-1, e^0], [e^-20, e^-10, e^0]]
print('sum', np.sum(np.exp(vec - np.max(vec, axis=-1, keepdims=True)), axis=-1, keepdims=True)) # [[e^-1 + e^0 + e^-2], [e^-2 + e^-1 + e^0], [e^-20 + e^-10 + e^0]]

max [[ 2]
 [ 1]
 [10]]
diff [[ -1   0  -2]
 [ -2  -1   0]
 [-20 -10   0]]
exp [[3.67879441e-01 1.00000000e+00 1.35335283e-01]
 [1.35335283e-01 3.67879441e-01 1.00000000e+00]
 [2.06115362e-09 4.53999298e-05 1.00000000e+00]]
sum [[1.50321472]
 [1.50321472]
 [1.0000454 ]]


In [17]:
softmax(vec)

array([[2.44728471e-01, 6.65240956e-01, 9.00305732e-02],
       [9.00305732e-02, 2.44728471e-01, 6.65240956e-01],
       [2.06106005e-09, 4.53978686e-05, 9.99954600e-01]])