1. numpy 모듈의 호출

In [1]:
import numpy as np

2. array의 생성

In [2]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [16]:
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)
print(test_array.dtype)
print(test_array.shape) # 매트릭스 크기 - 1차원배열 4, 
print(test_array.ndim)  # 몇 차원 배열
print(test_array.size)  # 엘리먼트 총 갯수

[1. 4. 5. 8.]
float64
(4,)
1
4


In [17]:
test_array = np.array([[1, 2, 3, 4], [1, 2]])
print(test_array)
print(test_array.dtype)
print(test_array.shape) # 배열의 크기가 다르면, 1차원 배열로 본다
print(test_array.ndim)
print(test_array.size)

[list([1, 2, 3, 4]) list([1, 2])]
object
(2,)
1
2


/var/folders/75/fxnqr1vj31784wlwqckw0n4w0000gn/T/ipykernel_97651/2288474582.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  test_array = np.array([[1, 2, 3, 4], [1, 2]])


In [19]:
test_array = np.array([[1, 2, 3, 4], [1, 2, 3, 4]], float)
print(test_array)
print(test_array.dtype)
print(test_array.shape) # 배열의 크기가 같아야, 2차원 배열로 본다
print(test_array.ndim)
print(test_array.size)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
float64
(2, 4)
2
8
